name: build
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    steps:
    - uses: actions/checkout@master
    - name: Dockerbuild
      uses: docker/build-push-action@v1.1.0
      with:
        add_git_labels: true
        tag_with_ref: true
        registry: docker.pkg.github.com
        repository: ${{github.repository}}/dcollect
        username: ${{ github.actor }}
        password: ${{ github.token }}
